server:
  port: 8086
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5431/crypto?stringtype=unspecified
    username: root
    password: root

binance:
  multiply: 100000000
  api:
    key: E6lAL4UM9JgEInLogyAvaGfgbXklcF3xGCNkW4FwBx1pIkPJnJsbtr1Dm4HkDlGB
    secret: RtJpEZsuOFX1NVp242d5fhcIwU5ULSjvC7MiUzv0dnu20oNylkTk0TRYKWfmMOcl